##################################################
########## 1D histograms #########################
##################################################

h1_deltaT_4min:
  type: "hist1"
  entries:
    deltaT_tL:
      plot: "{DT}.Eval(4)"
      read:
        DT: "g_DeltaTTopL"
      label: "Top left"
      color: 2
      fillstyle: 0
    deltaT_tR:
      plot: "{DT}.Eval(4)"
      read:
        DT: "g_DeltaTTopR"
      label: "Top right"
      color: 800
      fillstyle: 0
    deltaT_bL:
      plot: "{DT}.Eval(4)"
      read:
        DT: "g_DeltaTBottomL"
      label: "Bottom left"
      color: 4
      fillstyle: 0
    deltaT_bR:
      plot: "{DT}.Eval(4)"
      read:
        DT: "g_DeltaTBottomR"
      label: "Bottom right"
      color: 6
      fillstyle: 0
    deltaT_avg:
      plot: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
      label: "Avg."
      color: 1
      fillstyle: 0
  xmin: -23
  xmax: -15
  nbins: 80
  xtitle: "#DeltaT at 4 min. [#circC]"
  ytitle: "Entries"
  gridx: True
  gridy: False
  labelmode: "stddev_by_mean"


h1_deltaTcorr_4min:
  type: "hist1"
  entries:
    deltaT_tL:
      plot: "-0.099*(25.5 - {refT}) + {DT}.Eval(4)"
      def:
        refT: 0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33))
      read:
        DT: "g_DeltaTTopL"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      label: "Top left"
      color: 2
      fillstyle: 0
    deltaT_tR:
      plot: "-0.099*(25.5 - {refT}) + {DT}.Eval(4)"
      def:
        refT: 0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33))
      read:
        DT: "g_DeltaTTopR"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      label: "Top right"
      color: 800
      fillstyle: 0
    deltaT_bL:
      plot: "-0.099*(25.5 - {refT}) + {DT}.Eval(4)"
      def:
        refT: 0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33))
      read:
        DT: "g_DeltaTBottomL"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      label: "Bottom left"
      color: 4
      fillstyle: 0
    deltaT_bR:
      plot: "-0.099*(25.5 - {refT}) + {DT}.Eval(4)"
      def:
        refT: 0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33))
      read:
        DT: "g_DeltaTBottomR"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      label: "Bottom right"
      color: 6
      fillstyle: 0
    deltaT_avg:
      plot: "-0.099*(25.5 - {refT}) + {avgDT}"
      def:
        avgDT: numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])
        refT: 0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33))
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      label: "Avg."
      color: 1
      fillstyle: 0
  xmin: -23
  xmax: -15
  nbins: 80
  xtitle: "#DeltaT at 4 min. [#circC]"
  ytitle: "Entries"
  gridx: True
  gridy: False
  labelmode: "stddev_by_mean"




h1_deltaT-std_4min:
  type: "hist1"
  entries:
    deltaT_avg:
      plot: "numpy.std([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
      label: "At 4 min."
      color: 1
      fillstyle: 3001
  xmin: 0
  xmax: 1
  nbins: 50
  xtitle: "#sigma(#DeltaT) [#circC]"
  ytitle: "Entries"
  gridx: True
  gridy: False
  labelmode: "stddev_by_mean"


##################################################
########## 1D graphs #############################
##################################################


g1_deltaT_vs_barcode:
  type: "graph"
  entries:
    deltaT_avg_vs_barcode:
      plotx: "int('{barcode}'.split('3211004000')[1])"
      ploty: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
      fit:
        pol0: "[0]+([1]*x)"
      label: "Avg."
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 100
  xmax: 1400
  ymin: -23
  ymax: -15
  xtitle: "DM barcode [prefix 3211004000]"
  ytitle: "#DeltaT at 4 min. [#circC]"
  gridx: True
  gridy: True


g1_deltaT-std_vs_barcode:
  type: "graph"
  entries:
    deltaT-std_vs_barcode:
      plotx: "int('{barcode}'.split('3211004000')[1])"
      ploty: "numpy.std([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
      fit:
        pol0: "[0]+([1]*x)"
      label: "At 4 min."
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 100
  xmax: 1400
  ymin: 0
  ymax: 1
  xtitle: "DM barcode [prefix 3211004000]"
  ytitle: "#sigma(#DeltaT) [#circC]"
  gridx: True
  gridy: True


g1_deltaT-std_vs_tec-std:
  type: "graph"
  entries:
    deltaT-std_vs_tec-std:
      plotx: "numpy.std([{sm1}['sipm1']['tec_res'], {sm1}['sipm2']['tec_res'], {sm2}['sipm1']['tec_res'], {sm2}['sipm2']['tec_res']])"
      ploty: "numpy.std([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
      fit:
        pol0: "[0]+([1]*x)"
      label: "At 4 min."
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
      labelmode: "corr"
  xmin: 0
  xmax: 0.5
  ymin: 0
  ymax: 1
  xtitle: "#sigma(R_{TEC}) [#Omega]"
  ytitle: "#sigma(#DeltaT) [#circC]"
  gridx: True
  gridy: True
  labelmode: "corr"


g1_deltaT-std_vs_deltaT-avg:
  type: "graph"
  entries:
    deltaT-std_vs_deltaT-avg:
      plotx: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      ploty: "numpy.std([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
      fit:
        pol0: "[0]+([1]*x)"
      label: "At 4 min."
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
      labelmode: "corr"
  xmin: -23
  xmax: -15
  ymin: 0
  ymax: 1
  xtitle: "Avg. #DeltaT [#circC]"
  ytitle: "#sigma(#DeltaT) [#circC]"
  gridx: True
  gridy: True
  labelmode: "corr"


g1_deltaT-avg_vs_tec-sum:
  type: "graph"
  entries:
    deltaT-avg_vs_tec-sum:
      plotx: "numpy.sum([{sm1}['sipm1']['tec_res'], {sm1}['sipm2']['tec_res'], {sm2}['sipm1']['tec_res'], {sm2}['sipm2']['tec_res']])"
      ploty: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
      fit:
        pol0: "[0]+([1]*x)"
      label: "At 4 min."
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 45
  xmax: 55
  ymin: -23
  ymax: -15
  xtitle: "#Sigma(R_{TEC}) [#Omega]"
  ytitle: "Avg. #DeltaT [#circC]"
  gridx: True
  gridy: True
  labelmode: "corr"


g1_deltaT-avg_vs_power:
  type: "graph"
  entries:
    deltaT-avg_vs_power:
      plotx: "{pwr}.Eval(4)"
      ploty: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
        pwr: "g_power"
      fit:
        pol0: "[0]+([1]*x)"
      label: "At 4 min."
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 4
  xmax: 5.5
  ymin: -23
  ymax: -15
  xtitle: "Power drawn [W]"
  ytitle: "Avg. #DeltaT [#circC]"
  gridx: True
  gridy: True
  labelmode: "corr"


g1_deltaT-avg_vs_refT:
  type: "graph"
  entries:
    deltaT-avg_vs_refT:
      plotx: "0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33))"
      ploty: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 20
  xmax: 30
  ymin: -23
  ymax: -15
  xtitle: "CP temperature [#circC]"
  ytitle: "Avg. #DeltaT [#circC] at 4 min."
  gridx: True
  gridy: True
  labelmode: "corr"


g1_deltaT-avg_vs_refT-tec:
  type: "graph"
  entries:
    deltaT-avg_vs_refT:
      plotx: "{refT}"
      ploty: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      def:
        refT: numpy.mean([{refTL}.Eval(0.33), {refTR}.Eval(0.33), {refBL}.Eval(0.33), {refBR}.Eval(0.33)])
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
        refTL: "g_TTopL"
        refTR: "g_TTopR"
        refBL: "g_TBottomL"
        refBR: "g_TBottomR"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 20
  xmax: 30
  ymin: -23
  ymax: -15
  xtitle: "Initial temp. (RTD avg.) [#circC]"
  ytitle: "Avg. #DeltaT [#circC] at 4 min."
  gridx: True
  gridy: True
  labelmode: "corr"


g1_deltaT-avg_vs_ref-deltaT:
  type: "graph"
  entries:
    deltaT-avg_vs_ref-deltaT:
      plotx: "0.5*(({refL}.Eval(4)+{refR}.Eval(4)) - ({refL}.Eval(0.33)+{refR}.Eval(0.33)))"
      ploty: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 0
  xmax: 5
  ymin: -23
  ymax: -15
  xtitle: "#Delta(CP temperature) [#circC]"
  ytitle: "Avg. #DeltaT [#circC] at 4 min."
  gridx: True
  gridy: True
  labelmode: "corr"


g1_deltaT-avg_vs_deltaT-offset:
  type: "graph"
  entries:
    deltaT-avg_vs_deltaT-offset:
      plotx: "0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33)) - numpy.mean([{refTL}.Eval(0.33), {refTR}.Eval(0.33), {refBL}.Eval(0.33), {refBR}.Eval(0.33)])"
      ploty: "numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])"
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
        refTL: "g_TTopL"
        refTR: "g_TTopR"
        refBL: "g_TBottomL"
        refBR: "g_TBottomR"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: -3
  xmax: 3
  ymin: -23
  ymax: -15
  xtitle: "#DeltaT offset (CP - TEC) [#circC]"
  ytitle: "Avg. #DeltaT [#circC] at 4 min."
  gridx: True
  gridy: True
  labelmode: "corr"


g1_deltaTcorr-avg_vs_refT:
  type: "graph"
  entries:
    deltaTcorr-avg_vs_refT:
      plotx: "{refT}"
      ploty: "-0.099*(25.5 - {refT}) + {avgDT}"
      def:
        refT: 0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33))
        avgDT: numpy.mean([{tL}.Eval(4), {tR}.Eval(4), {bL}.Eval(4), {bR}.Eval(4)])
      read:
        tL: "g_DeltaTTopL"
        tR: "g_DeltaTTopR"
        bL: "g_DeltaTBottomL"
        bR: "g_DeltaTBottomR"
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 20
  xmax: 30
  ymin: -23
  ymax: -15
  xtitle: "CP temperature [#circC]"
  ytitle: "Avg. #DeltaT [#circC] at 4 min."
  gridx: True
  gridy: True
  labelmode: "corr"


g1_refT_vs_barcode:
  type: "graph"
  entries:
    refT_vs_barcode:
      plotx: "int('{barcode}'.split('3211004000')[1])"
      ploty: "0.5*({refL}.Eval(0.33)+{refR}.Eval(0.33))"
      read:
        refL: "g_TColdPlateL"
        refR: "g_TColdPlateR"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 100
  xmax: 1400
  ymin: 20
  ymax: 30
  xtitle: "DM barcode [prefix 3211004000]"
  ytitle: "CP temperature [#circC]"
  gridx: True
  gridy: True
  labelmode: "corr"


g1_power_vs_tec-sum:
  type: "graph"
  entries:
    power_vs_tec-sum:
      plotx: "numpy.sum([{sm1}['sipm1']['tec_res'], {sm1}['sipm2']['tec_res'], {sm2}['sipm1']['tec_res'], {sm2}['sipm2']['tec_res']])"
      ploty: "{pwr}.Eval(4)"
      read:
        pwr: "g_power"
      fit:
        pol0: "[0]+([1]*x)"
      label: "At 4 min."
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 45
  xmax: 55
  ymin: 4
  ymax: 5.5
  xtitle: "#Sigma(R_{TEC}) [#Omega]"
  ytitle: "Power drawn [W]"
  gridx: True
  gridy: True
  labelmode: "corr"


g1_tec-sum_vs_barcode:
  type: "graph"
  entries:
    tec-sum_vs_barcode:
      plotx: "int('{barcode}'.split('3211004000')[1])"
      ploty: "numpy.sum([{sm1}['sipm1']['tec_res'], {sm1}['sipm2']['tec_res'], {sm2}['sipm1']['tec_res'], {sm2}['sipm2']['tec_res']])"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 100
  xmax: 1400
  ymin: 45
  ymax: 55
  xtitle: "DM barcode [prefix 3211004000]"
  ytitle: "#Sigma(R_{TEC}) [#Omega]"
  gridx: True
  gridy: True
  labelmode: "corr"


g1_tec-sum-bac_vs_barcode:
  type: "graph"
  entries:
    tec-sum-bac_vs_barcode:
      plotx: "int('{barcode}'.split('3211004000')[1])"
      ploty: "{extra}['tec_sum_bac']"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 100
  xmax: 1400
  ymin: 45
  ymax: 55
  xtitle: "DM barcode [prefix 3211004000]"
  ytitle: "#Sigma(R_{TEC}) at BAC [#Omega]"
  gridx: True
  gridy: True
  labelmode: "corr"


g1_tec-sum-bac_vs_tec-sum:
  type: "graph"
  entries:
    tec-sum-bac_vs_tec-sum:
      plotx: "numpy.sum([{sm1}['sipm1']['tec_res'], {sm1}['sipm2']['tec_res'], {sm2}['sipm1']['tec_res'], {sm2}['sipm2']['tec_res']])"
      ploty: "{extra}['tec_sum_bac']"
      fit:
        pol0: "[0]+([1]*x)"
      label: ""
      color: 1
      marker: 4
      size: 1
      drawopt: "P"
  xmin: 45
  xmax: 55
  ymin: 45
  ymax: 60
  xtitle: "#Sigma(R_{TEC}) [#Omega]"
  ytitle: "#Sigma(R_{TEC}) at BAC [#Omega]"
  gridx: True
  gridy: True
  labelmode: "corr"