categories:
  X: ('D' in '{sm_cat}') or ('R' in '{sm_cat}')
  A: "(not {deltaT_sig_high}) and (not {deltaT_avg_sig_high}) and (not {X}) and ({nfoamlayers} == 1)"
  B: "(not {deltaT_sig_high}) and (not {deltaT_avg_sig_high}) and (not {X}) and ({nfoamlayers} == 2)"
  R: "({deltaT_sig_high} or {deltaT_avg_sig_high}) and (not {X})"
  #R: "not {A}"


metrics:
  
  deltaT_sig_high: "bool(max({tL_sig}, {tR_sig}, {bL_sig}, {bR_sig}) > {deltaT_sig_max})"
  deltaT_avg_sig_high: "bool({avg_sig} > {deltaT_avg_sig_max})"
  
  deltaT_high: "bool(max({tL}, {tR}, {bL}, {bR}) > {deltaT_max})"
  deltaT_avg_high: "bool(numpy.mean([{tL}, {tR}, {bL}, {bR}]) > {deltaT_avg_max})"
  
  deltaT_avg: "float(numpy.mean([{tL}, {tR}, {bL}, {bR}]))"
  deltaT_std: "float(numpy.std([{tL}, {tR}, {bL}, {bR}]))"
  deltaT_min: "float(numpy.min([{tL}, {tR}, {bL}, {bR}]))"
  deltaT_max: "float(numpy.max([{tL}, {tR}, {bL}, {bR}]))"
  
  sm_cat: "str({sm1}['results']['category']+{sm2}['results']['category'])"
  
  tec_sum: "float(numpy.sum([{sm1}['sipm1']['tec_res'], {sm1}['sipm2']['tec_res'], {sm2}['sipm1']['tec_res'], {sm2}['sipm2']['tec_res']]))"
  tec_std: "float(numpy.std([{sm1}['sipm1']['tec_res'], {sm1}['sipm2']['tec_res'], {sm2}['sipm1']['tec_res'], {sm2}['sipm2']['tec_res']]))"
  
  lo_avg: "-0.5*({sm1}['results']['lo_bar_avg'] + {sm2}['results']['lo_bar_avg'])"
  
  nfoamlayers: "{extra}['nfoamlayers']"
  
  # Negative for reverse sorting
  grouping: "-0.5*({sm1}['results']['lo_bar_avg'] + {sm2}['results']['lo_bar_avg'])"


# Will print the metrics for each RU
# The RU DMs can be accessed as ru.dms
# The above metrics can be accessed here as dm.results['metric_name'], where dm is an element of ru.dms
# Results/metrics of the constituent SMs can be accessed here as dm.sm<1/2>.results['metric_name'] 
ru_metrics:
  
  #lo_avg_ru: "numpy.mean([_dm.results['lo_avg'] for _dm in ru.dms])"
  #lo_std_ru: "numpy.std([_dm.results['lo_avg'] for _dm in ru.dms])"
  
  lo_avg_ru: "numpy.mean([[_sm.results['lo_bar_avg'] for _sm in [_dm.sm1, _dm.sm2]] for _dm in ru.dms])"
  lo_std_ru: "numpy.std([[_sm.results['lo_bar_avg'] for _sm in [_dm.sm1, _dm.sm2]] for _dm in ru.dms])"
  lo_min_ru: "numpy.min([[_sm.results['lo_bar_avg'] for _sm in [_dm.sm1, _dm.sm2]] for _dm in ru.dms])"
  lo_max_ru: "numpy.max([[_sm.results['lo_bar_avg'] for _sm in [_dm.sm1, _dm.sm2]] for _dm in ru.dms])"
  
  lo_std_rel_ru: "100*{lo_std_ru}/{lo_avg_ru}"
  lo_delta_rel_ru: "100*({lo_max_ru}-{lo_min_ru})/{lo_avg_ru}"
  
  deltaT_avg_ru: "numpy.mean([_dm.results['deltaT_avg'] for _dm in ru.dms])"
  deltaT_std_ru: "numpy.std([_dm.results['deltaT_avg'] for _dm in ru.dms])"
  deltaT_min_ru: "numpy.min([_dm.results['deltaT_min'] for _dm in ru.dms])"
  deltaT_max_ru: "numpy.max([_dm.results['deltaT_max'] for _dm in ru.dms])"

  tec_avg_ru: "numpy.mean([_dm.results['tec_sum'] for _dm in ru.dms])"
  tec_std_ru: "numpy.std([_dm.results['tec_sum'] for _dm in ru.dms])"


# Will print the metrics for each Tray
# The Tray RUs can be accessed as tray.rus
# The RU metrics can be accessed here as ru.results['metric_name'], where ru is an element of tray.rus
tray_metrics:
  
  lo_avg_tray: "numpy.mean([_ru.results['lo_avg_ru'] for _ru in tray.rus])"
  lo_ru_std_tray: "numpy.std([_ru.results['lo_avg_ru'] for _ru in tray.rus])"
  lo_ru_min_tray: "numpy.min([_ru.results['lo_avg_ru'] for _ru in tray.rus])"
  lo_ru_max_tray: "numpy.max([_ru.results['lo_avg_ru'] for _ru in tray.rus])"
  
  lo_ru_std_rel_tray: "100*{lo_ru_std_tray}/{lo_avg_tray}"
  lo_ru_delta_rel_tray: "100*({lo_ru_max_tray}-{lo_ru_min_tray})/{lo_avg_tray}"


def:
  tL: "{gtL}.Eval(4)"
  tR: "{gtR}.Eval(4)"
  bL: "{gbL}.Eval(4)"
  bR: "{gbR}.Eval(4)"
  
  tL_sig: "({gtL}.Eval(4) - {tL_mu}) / {tL_sigma}"
  tR_sig: "({gtR}.Eval(4) - {tR_mu}) / {tR_sigma}"
  bL_sig: "({gbL}.Eval(4) - {bL_mu}) / {bL_sigma}"
  bR_sig: "({gbR}.Eval(4) - {bR_mu}) / {bR_sigma}"
  avg_sig: "(numpy.mean([{gtL}.Eval(4), {gtR}.Eval(4), {gbL}.Eval(4), {gbR}.Eval(4)]) - {avg_mu}) / {avg_sigma}"


read:
  gtL: "g_DeltaTTopL"
  gtR: "g_DeltaTTopR"
  gbL: "g_DeltaTBottomL"
  gbR: "g_DeltaTBottomR"


values:
  tL_mu: -18.86
  tL_sigma: 0.59
  
  tR_mu: -18.73
  tR_sigma: 0.53
  
  bL_mu: -18.79
  bL_sigma: 0.59
  
  bR_mu: -18.65
  bR_sigma: 0.52
  
  avg_mu: -18.75
  avg_sigma: 0.46
  
  deltaT_sig_max: 4
  deltaT_avg_sig_max: 4
  
  deltaT_max: -18
  deltaT_avg_max: -18