run_types:
  dm_check:
    srcs: ["{plotsdir}/tofhir/plots_dmPosition_runs_{runstart}_{runend}"]
    #exclude: ["counts*.json"]
  tp:
    srcs: ["{plotsdir}/tofhir/plots_run_{run}"]
  lyso:
    srcs: ["{plotsdir}/tofhir/plots_run_{run}"]
  disc:
    srcs: ["{plotsdir}/disc_scan/run_{run}"]
  iv:
    srcs: ["{plotsdir}/iv_scan/run_{run}"]
  tec:
    srcs: ["{plotsdir}/temps/run_{run}"]
  calibrate:
    srcs: [
      "{runsdir}/FE_calibs/{tray}_{ru}",
      "{plotsdir}/tofhir_calibs/run_{run}"
    ]